### ISSUE TITLE
Add file in META-INF ?

### ISSUE THREAD

**Issue by lohic** [Grandt/PHPePub#32]
Hello, I can't find a way with the library to add a file in the META-INF folder (I'm trying to add com.apple.ibooks.display-options.xml to be able to force embed font in apple pub reading software).

Is there a way to do it ?

For the moment, I'm using the ZipArchive php class and add it after my pub generation.

**Comment by Grandt** [comment]
Bloody Apple and their proprietary ways of doing normal things.

I'll look into it and see if I can have an update ready today.

**Comment by Grandt** [comment]
I just released Rev. 4.0.2
* Changed: Added function addFileToMETAINF to enable users to add the apple ibooks metadata.
*   $book->addFileToMETAINF("com.apple.ibooks.display-options.xml", $xmldata);

**Comment by lohic** [comment]
Hello @Grandt ,

Thank you for this really quick update, that works perfectly.
