### ISSUE TITLE
Pathinfo extension undefined

### ISSUE THREAD

**Issue by tcitworld** [Grandt/PHPePub#37]
I exported two articles containing a lot of different pictures and some of them seem to not return any information through pathinfo, leading to failure. 
Therefore, `pathinfo($internalSrc);` returns undefined [here](https://github.com/Grandt/PHPePub/blob/master/src/PHPePub/Core/EPub.php#L601). It should be tested before next conditional.

**Comment by Grandt** [comment]
Do you happen to have an example of a path leading to an undefined return from pathinfo?
I'm adding `$iSrcInfo != null && ` to the if statement following the call, that should protect it if pathinfo returns an undefined result.

**Comment by tcitworld** [comment]
The two articles were [this one](https://zestedesavoir.com/tutoriels/1116/les-architectures-tolerantes-aux-pannes-et-aux-erreurs/) and [this other one](https://zestedesavoir.com/articles/1063/lequipe-de-developpement-de-zeste-de-savoir-recrute/). There's at least two different pictures concerned.

**Comment by Grandt** [comment]
So the issue is not that `pathinfo` returns an undefined result, but that `$iSrcInfo['extension']` is undefined as the link doesn't always have an extension.

I'll apply a fix for that assumption, and post 4.0.7 in a few minutes.

**Comment by tcitworld** [comment]
I thought so too, but I seem to recall to have *var_dumped* `$iSrcInfo` once without success.

**Comment by Grandt** [comment]
pathinfo shouldn't return an undefined at all. Try 4.0.7 I just posted to packagist, if that fails, I'll have to check further.

**Comment by tcitworld** [comment]
Works fine. :+1:
